scripts:

  procure-install-nodejs:
    exclusive_executor_resource: asdf-nodjes
    body: |
      cd $LEIHS_PROCURE_DIR
      ./bin/env/nodejs-setup

  procure-service-run:
    timeout: 15 Minutes
    start_when:
      uberjar has been built:
        script_key: procure-uberjar-build
      database has been created:
        script_key: create-database
      nodejs is installed:
        script_key: procure-install-nodejs
    body: |
      #!/usr/bin/env bash
      set -euo pipefail
      cd $LEIHS_PROCURE_DIR/server
      export DB_NAME=${LEIHS_DATABASE_NAME}
      export HTTP_PORT=${LEIHS_PROCURE_HTTP_PORT}
      mkdir tmp
      unset PGPORT; unset PGUSER
      PGPORT=$PG10PORT PGUSER=$PG10USER ./bin/run --pid-file tmp/service.pid

  procure-service-is-running:
    body: |
      #!/usr/bin/env bash
      set -euo pipefail
      until curl --silent --fail -I \
        -H 'Accept: application/json' \
        "http://localhost:${LEIHS_PROCURE_HTTP_PORT}/procure/status";
        do sleep 1;
      done
    start_when:
      run server is executing:
        script_key: procure-service-run
        states: [executing]

  test:
    start_when:
      procure service is running:
        script_key: procure-service-is-running

  shutdown-procure-service:
    body: |
      #!/usr/bin/env bash
      set -euo pipefail
      cd $LEIHS_PROCURE_DIR/server
      export PID=$(cat tmp/service.pid)
      kill $PID
      tail --pid=$PID -f /dev/null
    start_when:
      test is terminal:
        script_key: test
        states: [aborted, defective, passed, failed, skipped]

  delete-database:
    start_when:
      shutdown-procure-service is in terminal state:
        script_key: shutdown-procure-service
        states: [aborted, defective, passed, failed, skipped]
