include:
  - cider-ci/task-components/asdf-nodejs.yml

scripts:

  admin-service-run:
    start_when:
      nodejs is installed:
        script_key: admin-nodejs-asdf-install
      uberjar has been built:
        script_key: admin-build-uberjar
      database has been created:
        script_key: create-database
    body: |
      #!/usr/bin/env bash
      set -euo pipefail
      export HTTP_PORT=${LEIHS_ADMIN_HTTP_PORT}
      cd $LEIHS_ADMIN_DIR
      mkdir -p $LEIHS_ADMIN_DIR/tmp
      unset PGPORT
      unset PGUSER
      PGPORT=${PG10PORT} PGUSER=${PG10USER} java \
        -jar target/leihs-admin.jar \
        run --pid-file tmp/service.pid

  admin-service-is-running:
    body: |
      #!/usr/bin/env bash
      set -euo pipefail
      until curl --silent --fail -I \
        -H 'Accept: application/json' \
        "http://localhost:${LEIHS_ADMIN_HTTP_PORT}/admin/status";
        do sleep 1;
      done
    start_when:
      run server is executing:
        script_key: admin-service-run
        states: [executing]

  test:
    start_when:
      admin service is running:
        script_key: admin-service-is-running

  shutdown-admin-service:
    body: |
      #!/usr/bin/env bash
      set -euo pipefail
      cd $LEIHS_ADMIN_DIR
      export PID=$(cat tmp/service.pid)
      kill $PID
      tail --pid=$PID -f /dev/null
    start_when:
      test is terminal:
        script_key: test
        states: [aborted, defective, passed, failed, skipped]

  delete-database:
    start_when:
      shutdown-admin-service is in termial state:
        script_key: shutdown-admin-service
        states: [aborted, defective, passed, failed, skipped]
