name: LEIHS/leihs/admin
windows:
  2:
    name: server-dev
    command: |
      ./bin/dev-run-backend
  3:
    name: front-dev
    command: |
      bin/dev-run-frontend
  5:
    name: psql
    command: |
      psql -d leihs
  6:
    name: db
    command: |
      cd database
  7:
    name: test
    command: |
      export LEIHS_DATABASE_URL="postgresql://localhost:5432/leihs?max-pool-size=5"
      export LEIHS_ADMIN_HTTP_BASE_URL=http://localhost:3220
      export RAILS_ENV=test
  8:
    name: shared-clj
    command: |
      cd shared-clj
