jobs:
  procure-build-uberjar:
    name: Build procure uberjar
    include: cider-ci/uberjar_job.yml

  backend-specs:
    name: 'Backend: Run specs'
    depends_on: &SPEC_DEPENDS
      uberjar was built:
        type: job
        job_key: procure-build-uberjar
        states: [passed]
    run_when: *SPEC_DEPENDS
    include: cider-ci/backend-specs_job.yml

  client-lint-and-specs:
    name: 'Client/Frontend: Lint and Specs'
    depends_on: *SPEC_DEPENDS
    run_when: *SPEC_DEPENDS
    include: cider-ci/client_job.yml

  feature-specs:
    name: Feature specs
    depends_on: *SPEC_DEPENDS
    run_when: *SPEC_DEPENDS
    include: cider-ci/feature-specs_job.yml

  good-to-merge:
    name: Good To Merge
    description: |
      This job depends on all other tests and checks
      and it will pass if and only if all dependencies have passed.
      Status of this job is **used by github's "branch protection"**!
    include: cider-ci/good-to-merge_job.yml
