#!/usr/bin/env bash

SCRIPT_FULL_PATH=$(realpath "$0")
SCRIPT_DIR=$(dirname $SCRIPT_FULL_PATH)

"$SCRIPT_DIR"/kill-all

tmux send -t leihs-admin:2.1 "LEIHS_DATABASE_URL=\"$LEIHS_DATABASE_URL\" lein do clean, repl :headless" C-m
tmux send -t leihs-admin:3.1 "./scripts/lein-auto-reset" C-m
tmux send -t leihs-admin:4.1 "tail -f log/debug.log" C-m
tmux send -t leihs-admin:5.1 "./bin/dev-run-frontend" C-m
