environment_variables:
  CI: 'true'
  LEIHS_DATABASE_NAME: leihs_{{CIDER_CI_TRIAL_ID}}
  DATABASE_NAME: '{{LEIHS_DATABASE_NAME}}'
  RUBY: '{{RUBY_ENGINE}}-{{RUBY_VERSION}}'
  RUBY_ENGINE: ruby
  RUBY_VERSION: 2.7.5
  RUBY_BUNDLER_VERSION: 2.3.3
  RAILS_ENV: production

  LEIHS_PROCURE_DIR: '{{CIDER_CI_WORKING_DIR}}'
  LEIHS_PROCURE_SPEC_DIR: '{{LEIHS_PROCURE_DIR}}/server'
  LEIHS_DATABASE_DIR: '{{LEIHS_PROCURE_DIR}}/server/database'

  DIST_IMAGE_NAME: 'leihs-procure'
  DIST_VERSION_NAME: 'trial-{{CIDER_CI_TRIAL_ID}}'

  RUNNER_IMAGE_NAME: 'leihs-procure-runner'
  RUNNER_IMAGE_VERSION: 'trial-{{CIDER_CI_TRIAL_ID}}'
  RUNNER_IMAGE_TAG: '{{RUNNER_IMAGE_NAME}}:{{RUNNER_IMAGE_VERSION}}'
  RUNNER_CONTAINER_NAME: 'leihs-procure-trial-{{CIDER_CI_TRIAL_ID}}'
