environment_variables:
  CI: 'true'
  LEIHS_DATABASE_NAME: leihs_{{CIDER_CI_TRIAL_ID}}
  DATABASE_NAME: '{{LEIHS_DATABASE_NAME}}'
  RAILS_ENV: production

  LEIHS_PROCURE_DIR: '{{CIDER_CI_WORKING_DIR}}'
  LEIHS_PROCURE_SPEC_DIR: '{{LEIHS_PROCURE_DIR}}/server'
  LEIHS_DATABASE_DIR: '{{LEIHS_PROCURE_DIR}}/server/database'

  DIST_PROCURE_IMAGE_NAME: 'leihs-procure'
  DIST_VERSION_NAME: 'trial-{{CIDER_CI_TRIAL_ID}}'

  RUNNER_PROCURE_IMAGE_NAME: 'leihs-procure-runner'
  RUNNER_PROCURE_IMAGE_VERSION: 'trial-{{CIDER_CI_TRIAL_ID}}'
  RUNNER_PROCURE_IMAGE_TAG: '{{RUNNER_PROCURE_IMAGE_NAME}}:{{RUNNER_PROCURE_IMAGE_VERSION}}'
  RUNNER_PROCURE_CONTAINER_NAME: 'leihs-procure-trial-{{CIDER_CI_TRIAL_ID}}'
