#!/bin/sh

# NOTE: profiles.cljs config broken for some reason, using ENV for now
# echo 'starting dev server with following config'
# echo ' - - - 8< - - - '
# cat ./profiles.clj
# echo ' - - - 8< - - - '

export LEIHS_SECRET="secret"
export LEIHS_PROCURE_HTTP_BASE_URL=${LEIHS_PROCURE_HTTP_BASE_URL:="http://localhost:3230"}
export LEIHS_DATABASE_URL=${LEIHS_DATABASE_URL:="jdbc:postgresql://localhost:5432/leihs_stable?max-pool-size=5"}

test -f resources/dev/log4j.properties \
  || cp resources/dev/log4j.properties.template resources/dev/log4j.properties

test -f profiles.clj \
  || cp profiles_template.clj profiles.clj

REPL_PORT_FILE="./.nrepl-port"

rm -f $REPL_PORT_FILE
lein clean

# start REPL in background, wait for file with port info
lein repl :headless &
until test -e $REPL_PORT_FILE; do sleep 1; done

# start the watcher
lein auto-reset

# when exiting this script, kill our process tree (child and grand-child processes etc)
trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT
