#!/bin/sh

# NOTE: profiles.cljs config broken for some reason, using ENV for now
# echo 'starting dev server with following config'
# echo ' - - - 8< - - - '
# cat ./profiles.clj
# echo ' - - - 8< - - - '

export LEIHS_SECRET="secret"
export LEIHS_PROCURE_HTTP_BASE_URL="http://localhost:3230"
export LEIHS_DATABASE_URL="jdbc:postgresql://localhost:5432/leihs_prod?max-pool-size=5"

test -f resources/dev/log4j.properties \
  || cp resources/dev/log4j.properties.template resources/dev/log4j.properties

lein clean
lein with-profile dev run "run"
